use strict;
use warnings;
use lib 't/lib';
use Test::More;

subtest 'import and export' => sub {
    subtest 'export from IMPORT_MODULES' => sub {
        my $warn;
        local $SIG{__WARN__} = sub { $warn = $_[0] };
        eval q{
            package runtime::export;

            use MyExport;

            joy;
        };
        ok !$@ or diag $@;
        ok !$warn, "no warnings generated by Import::Base" or diag $warn;
    };

    subtest 'export from IMPORT_BUNDLES' => sub {
        my $warn;
        local $SIG{__WARN__} = sub { $warn = $_[0] };
        eval q{
            package runtime::export;

            use MyExport 'bundles', 'subs';

            happiness;
            catdir;
        };
        ok !$@ or diag $@;
        ok !$warn, "no warnings generated by Import::Base" or diag $warn;
    };

    subtest 'export from argument list' => sub {
        my $warn;
        local $SIG{__WARN__} = sub { $warn = $_[0] };
        eval q{
            package runtime::export;

            use MyExport 'external', 'happiness';

            happiness;
            catdir;
        };
        ok !$@ or diag $@;
        ok !$warn, "no warnings generated by Import::Base" or diag $warn;
    };
};

subtest 'import and export and inheritance' => sub {
    my $warn;
    local $SIG{__WARN__} = sub { $warn = $_[0] };
    eval q{
        package runtime::export::inheritance;

        use MyExportInherited;

        joy;
    };
    ok !$@ or diag $@;
    ok !$warn, "no warnings generated by Import::Base" or diag $warn;
};

done_testing;
